language: c

services:
  - docker

before_install:
  - docker pull fedora
  - docker ps -a
  - docker run -it fedora bash
  - pwd
  - cat /etc/redhat-release


before_script:
    - autoreconf -i -f
    - $CLANG_SCAN_BUILD ./configure --disable-silent-rules $CONFIGURE_ARGS
script:
    - $CLANG_SCAN_BUILD make
    - $CLANG_SCAN_BUILD make check
    - make distcheck
    - rpmbuild --define "_tmpfilesdir /usr/lib/tmpfiles.d" -ta --nodeps tlog-*.tar.gz
    - test "x$DISTCHECK" = xyes && make distcheck || true
